services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Auth
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SMTP_EMAIL_FROM: account@effuse.chat
      SMTP_HOST: maildev
      SMTP_PORT: "1025"
      SMTP_USERNAME: test_user
      SMTP_PASSWORD: test_password

      DATABASE_PROVIDER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database

      JWT_KEY: secret_jwt_key_that_is_secret_and_hidden
      JWT_ISSUER: effuse.chat

      UI_ORIGIN: http://localhost:8081

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      MAILDEV_OUTGOING_USER: test_user
      MAILDEV_OUTGOING_PASS: test_password

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database
    volumes:
      - postgres:/var/lib/postgresql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.Migration
    depends_on:
      - postgres
    environment:
      DATABASE_PROVIDER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database

volumes:
  postgres:
