FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /app

COPY . .

RUN dotnet restore

WORKDIR /app/Effuse.Auth

RUN dotnet publish -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

EXPOSE 8080

COPY --from=build /app/Effuse.Auth/out .
ENTRYPOINT ["./Effuse.Auth"]