version: '3'

tasks:
  restore: dotnet restore

  build:
    cmds:
      - dotnet build Effuse.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
    sources:
      - Effuse.Auth/**/*.cs
      - Effuse.Server/**/*.cs
      - Effuse.Core/**/*.cs
    generates:
      - Effuse.Auth/bin/**/*
      - Effuse.Server/bin/**/*
      - Effuse.Core/bin/**/*

  run:auth:
    deps:
      - build
    cmd: dotnet run --project ./Effuse.Auth/Effuse.Auth.csproj
    env:
      ASPNETCORE_ENVIRONMENT: Development

  run:server:
    deps:
      - build
    cmd: dotnet run --project ./Effuse.Server/Effuse.Server.csproj
    env:
      ASPNETCORE_ENVIRONMENT: Development

  run:
    deps:
      - run:auth
      - run:server

  test:
    dir: "{{.TASKFILE_DIR}}/Effuse.ApiTests"
    cmd: npm run test

  migrate:auth:
    dir: "{{.TASKFILE_DIR}}/Effuse.AuthMigration"
    cmd: npm run migrate:latest

  migrate:server:
    dir: "{{.TASKFILE_DIR}}/Effuse.ServerMigration"
    cmd: npm run migrate:latest

  migrate:
    cmds:
      - task: migrate:auth
      - task: migrate:server