services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app:cached
      - vscode:/root/.vscode-server
    command: sleep infinity
    user: root
    environment:
      SMTP_EMAIL_FROM: account@effuse.chat
      SMTP_HOST: maildev
      SMTP_PORT: "1025"
      SMTP_USERNAME: test_user
      SMTP_PASSWORD: test_password

      DATABASE_PROVIDER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database

      EFFUSE_POSTGRES_HOST: server-postgres
      EFFUSE_POSTGRES_USER: postgres
      EFFUSE_POSTGRES_DB: effuse
      EFFUSE_POSTGRES_PASSWORD: test_database

      JWT_KEY: secret_jwt_key_that_is_secret_and_hidden
      JWT_ISSUER: effuse.chat

      EFFUSE_URL: http://localhost:5171
      MAILDEV_URL: http://maildev:1080

      UI_ORIGIN: http://localhost:8081

      SERVER_URL: http://localhost:5153

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      MAILDEV_OUTGOING_USER: test_user
      MAILDEV_OUTGOING_PASS: test_password

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database

  server-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: effuse
      POSTGRES_PASSWORD: test_database

volumes:
  vscode:
